name: main

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10']
        continue-on-error: [false]
        include:
          - ghc: latest
            continue-on-error: true

    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.continue-on-error }}

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: $HOME/.cabal/packages
          key: packages-${{ runner.os }}-${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: $HOME/.cabal/store
          key: store-${{ runner.os }}-${{ matrix.ghc }}
      - run: make build-deps
      - run: make build
        env:
          CABAL_OPTIONS: --ghc-options -Werror
      - run: make doctest
      - run: make spec

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - uses: actions/cache@v2
        with:
          path: $HOME/.cabal/packages
          key: packages-${{ runner.os }}-latest
      - uses: actions/cache@v2
        with:
          path: $HOME/.cabal/store
          key: store-${{ runner.os }}-latest
      - run: cabal install hlint
      - run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH
      - run: make lint
