name: main

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0', '9.2']
        test: [doctest, spec]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: |
            $HOME/.cabal/packages
            $HOME/.cabal/store
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}
      - run: make build-deps
      - run: make build
      - run: make ${{ matrix.test }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
      - run: make lint
